### PR TITLE
Minor changes to README

### PR DESCRIPTION
**Pull request by cdrage**
Updates the readme with a brief description.

Removes the .gif for now (let's redo this and try to make it more simple
/ less amount of terminal flair).

Reorganizes the structure of README a little bit.

### CODE REVIEW

**Comment by cdrage** [comment]
ping @surajssd @kadel @containscafeine

**Comment by kadel** [comment]
leaving this on @surajssd

**Comment by cdrage** [comment]
rebased. ping @surajssd :)

**Comment by pradeepto** [comment]
LGTM. Let's merge but do note that we have to update this readme in a few days again.

**Pull request merged**
