### PR TITLE
Don't create pod Volume if there already is one with the same name

### LINKED ISSUE #34: volume entry in PodSpec is generated every time volume is used
```yaml
name: test

containers:
- image: quay.io/tomkral/nonroot-nginx
  name: nginx
  volumeMounts:
    - mountPath: /var/lib/nginx
      name: test
- image: quay.io/tomkral/sleeper
  name: data
  volumeMounts:
    - mountPath: /data
      name: test

services:
  - name: test
    type: LoadBalancer
    ports:
      - port: 8080

persistentVolumes:
  - name: test
    size: 500Mi
```

outputs invalid deployment:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
      name: test
    spec:
      containers:
      - image: quay.io/tomkral/nonroot-nginx
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/nginx
          name: test
      - image: quay.io/tomkral/sleeper
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: test
      volumes:
      - name: test
        persistentVolumeClaim:
          claimName: test
      - name: test
        persistentVolumeClaim:
          claimName: test
status: {}
```

There should be only one entry for each PVC.

### PR DESCRIPTION
**Pull request by kadel**
fixes #34

### CODE REVIEW

**Comment by surajssd** [comment]
@kadel what you have done is right but not complete, we cannot allow two `persistentVolumes` of same name, so this should also fail somewhere.

**Comment by surajssd** [comment]
@kadel also I am collecting the artifacts with corner cases in `tests/cmd/<corner case name>/artifact.yaml` this will help us add test later. In this way we will not miss out on anything later when adding tests. So basically collecting test data.

**Comment by surajssd** [comment]
@kadel checkout https://github.com/surajssd/kapp/pull/48/files to get context of what I am saying above!

**Comment by kadel** [comment]
> @kadel what you have done is right but not complete, we cannot allow two persistentVolumes of same name, so this should also fail somewhere.

That should be handled elsewhere. Two PersistentVolumes with the same name is something that validation should take care. This is in how Deployments is generated

**Comment by surajssd** [comment]
@kadel yes I agree do you want it to happen in different PR that is what you are saying? I thought one issue which has identified the problem will fix it as well!

**Comment by kadel** [comment]
yes, I would rather do it in separate PR. And refactor some other related parts of the code with it as well

**Comment by surajssd** [comment]
cool @kadel merging this created new issue WRT further addition https://github.com/surajssd/kapp/issues/55

**Pull request merged**
